### ISSUE TITLE
consume messages from before queue was created

### ISSUE THREAD

**Issue by ShahOdin** [ITV/bucky#35]
Starting with a blank rabbit container, I:

- publish a message X to an exchange
- start a consumer with a queue that does not exist
- I publish message Y

the consumer will see the message Y, but not X.

How can I configure the (consumer) client so that I can consume both?

**Comment by cmcmteixeira** [comment]
Hi @ShahOdin, that is expected behaviour! 
If a message is published but no queues are declared then it is expected that it would never be consumed because rabbit only holds information in queues and not at the exchange level.

**Comment by ShahOdin** [comment]
I see. so the messages for an exchange are lost if no queue is consuming them. that makes sense thanks.
